eolymp:
  apiurl: "https://api.eolymp.com"
  username: ""
  password: ""
  spaceimport: ""
polygon:
  login: ""
  password: ""
telegram:
  token: ""
  chatid: 0
  problems:
    - id: ""
      link: ""
      pid: ""
source: ""
spaceid: "00000000-0000-0000-0000-000000000000"
